version: 2.1
orbs:
node: circleci/node@3.0.0
workflows:
node-tests:
jobs:
  build: 
    docker:       
      - image: buildpack-deps:trusty        
    steps:       
      - run: echo "hello world"          t